---
- name: Build and Deploy Docker Image to Kubernetes
  hosts: localhost
  connection: local

  vars_files:
    - vault.yml

  vars:
    image_name: my-compte-service
    image_tag: "18"
    dockerfile_path: "./"
    namespace: jenkins
    kubeconfig_path: "~/.kube/config"

  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Build Docker image
      community.docker.docker_image:
        name: "hakim2002/{{ image_name }}"
        tag: "{{ image_tag }}"
        build:
          path: "{{ dockerfile_path }}"
        source: build
        state: present

    - name: Push the Docker image to Docker Hub
      community.docker.docker_image:
        name: "hakim2002/{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: local

    # Optional: verify image pull
    - name: Pull Docker image (optional)
      community.docker.docker_image:
        name: "hakim2002/{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: "{{ namespace }}"
        src: deployment.yaml
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        namespace: "{{ namespace }}"
        src: service.yaml
        kubeconfig: "{{ kubeconfig_path }}"
